# Generated by Django 4.2 on 2026-07-05 05:42

from django.db import migrations

def seed_services(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    # Clear old services to avoid orphaned records with old slugs
    Service.objects.all().delete()
    
    services = [
        # Govt Services
        {"name": "Senior Citizen Card", "slug": "apply_senior", "category": "Govt Services", "subcategory": "none", "cost": 50.00, "service_type": "Manual", "description": "Apply for Senior Citizen ID Card (Govt. of Karnataka)."},
        {"name": "Gruha Laxmi Sanction Order", "slug": "gl_sanction", "category": "Govt Services", "subcategory": "none", "cost": 30.00, "service_type": "Manual", "description": "Download Gruha Lakshmi Sanction Order."},
        {"name": "Gruha Laxmi Application", "slug": "gruhalaxmi", "category": "Govt Services", "subcategory": "none", "cost": 50.00, "service_type": "Manual", "description": "Submit new Gruha Lakshmi Scheme application."},
        {"name": "Gruha Laxmi Status", "slug": "gruhalaxmi_sts", "category": "Govt Services", "subcategory": "none", "cost": 30.00, "service_type": "Manual", "description": "Track the status of Gruha Lakshmi Application."},
        {"name": "Gruha Laxmi KYC", "slug": "gruhalaxmikyc", "category": "Govt Services", "subcategory": "none", "cost": 50.00, "service_type": "Manual", "description": "Update KYC details for Gruha Lakshmi Scheme."},
        {"name": "Gruha Jyothi", "slug": "gruhajyothi", "category": "Govt Services", "subcategory": "none", "cost": 50.00, "service_type": "Manual", "description": "Apply for free electricity under Gruha Jyothi scheme."},
        {"name": "Gruha Jyothi D-Link", "slug": "gruhajyothi_dlink", "category": "Govt Services", "subcategory": "none", "cost": 50.00, "service_type": "Manual", "description": "De-link meter registration details."},
        {"name": "Link Aadhaar & Pahani", "slug": "bhoomi_pahani_link", "category": "Govt Services", "subcategory": "none", "cost": 50.00, "service_type": "Manual", "description": "Link your Aadhaar card with Pahani/RTC land records."},
        {"name": "Download RTC", "slug": "rtc_download", "category": "Govt Services", "subcategory": "none", "cost": 10.00, "service_type": "Manual", "description": "Download Land RTC / Pahani."},
        {"name": "ABHA Card", "slug": "abha_card", "category": "Govt Services", "subcategory": "none", "cost": 50.00, "service_type": "Manual", "description": "Generate Ayushman Bharat Health Account Card."},
        {"name": "Ayushman Bharat Card", "slug": "ayush_card", "category": "Govt Services", "subcategory": "none", "cost": 100.00, "service_type": "Manual", "description": "Apply for Ayushman Bharat Card (PM-JAY)."},
        {"name": "AYUSH Download", "slug": "ayush_dwnld", "category": "Govt Services", "subcategory": "none", "cost": 50.00, "service_type": "Manual", "description": "Download Ayushman Bharat Card PDF."},
        {"name": "E-Shram Apply", "slug": "eshram", "category": "Govt Services", "subcategory": "none", "cost": 50.00, "service_type": "Manual", "description": "Register under e-Shram portal for unorganized workers."},
        {"name": "E-Shram Download", "slug": "eshram_dwnld", "category": "Govt Services", "subcategory": "none", "cost": 50.00, "service_type": "Manual", "description": "Download e-Shram UAN Card PDF."},
        {"name": "PM Kisan", "slug": "pmkisan", "category": "Govt Services", "subcategory": "none", "cost": 30.00, "service_type": "Manual", "description": "Apply, check status or do e-KYC for PM Kisan Samman Nidhi."},
        
        # Print Services - Ration Card
        {"name": "Ration Card Download", "slug": "rc_dwnld", "category": "Print Services", "subcategory": "Ration Card", "cost": 5.00, "service_type": "Automated", "description": "Instant Ration card PDF download using Card Number."},
        {"name": "Ration Card WITHOUT OTP", "slug": "slct_offlinedist", "category": "Print Services", "subcategory": "Ration Card", "cost": 5.00, "service_type": "Automated", "description": "Download Ration card without needing mobile OTP verification."},
        {"name": "Ration Shop & Member Details", "slug": "shop_select", "category": "Print Services", "subcategory": "Ration Card", "cost": 10.00, "service_type": "Manual", "description": "Fetch complete details of Ration shop and registered members."},
        {"name": "Anna Bhagya DBT Status", "slug": "annabhagya_view", "category": "Print Services", "subcategory": "Ration Card", "cost": 10.00, "service_type": "Manual", "description": "Check DBT cash transfer status under Anna Bhagya scheme."},
        {"name": "Correction Status", "slug": "corr_select", "category": "Print Services", "subcategory": "Ration Card", "cost": 10.00, "service_type": "Manual", "description": "Track the status of Ration Card corrections."},
        {"name": "Ration To Aadhaar", "slug": "ration_to_aadhaar", "category": "Print Services", "subcategory": "Ration Card", "cost": 50.00, "service_type": "Manual", "description": "Link Ration Card with Aadhaar database."},
        {"name": "Aadhaar To Ration", "slug": "aadhaar_to_ration", "category": "Print Services", "subcategory": "Ration Card", "cost": 50.00, "service_type": "Manual", "description": "Verify Aadhaar mapping in Ration database."},
        
        # Print Services - Voter ID
        {"name": "Name Correction", "slug": "epic_corrections_name", "category": "Print Services", "subcategory": "Voter Services", "cost": 100.00, "service_type": "Manual", "description": "Correct candidate's name on EPIC Voter Card."},
        {"name": "Update Mobile No.", "slug": "offline_mobile", "category": "Print Services", "subcategory": "Voter Services", "cost": 50.00, "service_type": "Manual", "description": "Link / Update mobile number registered with EPIC Voter Card."},
        {"name": "Photo Correction", "slug": "epic_corrections_photo", "category": "Print Services", "subcategory": "Voter Services", "cost": 50.00, "service_type": "Manual", "description": "Update candidate photo on EPIC Voter Card."},
        {"name": "Address Correction", "slug": "epic_corrections_address", "category": "Print Services", "subcategory": "Voter Services", "cost": 50.00, "service_type": "Manual", "description": "Correct residential address on EPIC Voter Card."},
        {"name": "Gender Correction", "slug": "epic_corrections_gender", "category": "Print Services", "subcategory": "Voter Services", "cost": 50.00, "service_type": "Manual", "description": "Correct gender details on EPIC Voter Card."},
        {"name": "DOB / Age Correction", "slug": "epic_corrections_dob", "category": "Print Services", "subcategory": "Voter Services", "cost": 50.00, "service_type": "Manual", "description": "Correct date of birth on EPIC Voter Card."},
        {"name": "Original Voter Card PDF Without OTP", "slug": "original_voter_pdf", "category": "Print Services", "subcategory": "Voter Services", "cost": 50.00, "service_type": "Automated", "description": "Download original Voter ID Card PDF without requiring mobile OTP."},
        {"name": "Voter Mobile Link Instant", "slug": "voter_mobile_instant", "category": "Print Services", "subcategory": "Voter Services", "cost": 50.00, "service_type": "Automated", "description": "Instantly link mobile number with Voter ID card using Aadhaar."},
        {"name": "Voter ID Download Instant", "slug": "voter_pdf_instant", "category": "Print Services", "subcategory": "Voter Services", "cost": 50.00, "service_type": "Automated", "description": "Instantly download Voter ID Card PDF via EPIC number."},
        
        # Print Services - DL
        {"name": "DL - All India PVC", "slug": "dlallindia", "category": "Print Services", "subcategory": "DL Services", "cost": 25.00, "service_type": "Automated", "description": "Instant All India Driving Licence PVC print data download."},
        {"name": "DL Karnataka PVC", "slug": "dl_karnataka", "category": "Print Services", "subcategory": "DL Services", "cost": 25.00, "service_type": "Automated", "description": "Instant Driving Licence PVC print data download for Karnataka."},
        {"name": "Find DL No.", "slug": "find_dlno", "category": "Print Services", "subcategory": "DL Services", "cost": 100.00, "service_type": "Manual", "description": "Find Driving Licence Number using Name and DOB."},
        {"name": "Link DL <> Mobile No.", "slug": "link_dltomobile", "category": "Print Services", "subcategory": "DL Services", "cost": 50.00, "service_type": "Manual", "description": "Link / Update mobile number on DL records."},
        
        # Print Services - Vehicle
        {"name": "Karnataka RC Advance", "slug": "rc_advance", "category": "Print Services", "subcategory": "Vehicle Services", "cost": 25.00, "service_type": "Manual", "description": "Request Vehicle RC details for Karnataka State."},
        {"name": "Vehicle RC All India PVC", "slug": "allind_adv", "category": "Print Services", "subcategory": "Vehicle Services", "cost": 25.00, "service_type": "Automated", "description": "Download RC details formatted for All-India PVC card printing."},
        {"name": "Vehicle RC Karnataka PVC", "slug": "rckar_pvc", "category": "Print Services", "subcategory": "Vehicle Services", "cost": 25.00, "service_type": "Automated", "description": "Download RC details formatted for Karnataka PVC card printing."},
        {"name": "Link Mobile No. to Veh. RC", "slug": "vrc_mobile", "category": "Print Services", "subcategory": "Vehicle Services", "cost": 50.00, "service_type": "Manual", "description": "Link / Update mobile number on vehicle registration records."},
        {"name": "LL Exam", "slug": "ll_exam", "category": "Print Services", "subcategory": "Vehicle Services", "cost": 150.00, "service_type": "Manual", "description": "Access Learner's Licence Exam portal."},
        
        # Print Services - PAN
        {"name": "PAN Card Print", "slug": "pan_card_print", "category": "Print Services", "subcategory": "PAN Services", "cost": 20.00, "service_type": "Automated", "description": "Instant PAN Card PDF download for PVC card printing."},
        {"name": "PAN Card Find", "slug": "aadhaar_panstatus", "category": "Print Services", "subcategory": "PAN Services", "cost": 30.00, "service_type": "Automated", "description": "Find PAN Card number instantly using Name, DOB and Aadhaar Number."},
        {"name": "Pan To Aadhaar", "slug": "pan_to_aadhaar", "category": "Print Services", "subcategory": "PAN Services", "cost": 200.00, "service_type": "Manual", "description": "Link PAN Card with Aadhaar database."},
        {"name": "Mobile to PAN Find", "slug": "pan_mobile_find", "category": "Print Services", "subcategory": "PAN Services", "cost": 25.00, "service_type": "Manual", "description": "Track and find PAN card number via registered mobile number."},
        
        # Other Services
        {"name": "Tailoring Certificate", "slug": "tailoring_certificate", "category": "Other Services", "subcategory": "none", "cost": 450.00, "service_type": "Manual", "description": "Apply for tailoring course certification and marksheets."},
        {"name": "Basic Computer Certificate", "slug": "basic_computer_certificate", "category": "Other Services", "subcategory": "none", "cost": 400.00, "service_type": "Manual", "description": "Apply for 3-Month Basic Computer Course certification."},
        {"name": "Udyam Registration", "slug": "udyam_registration", "category": "Other Services", "subcategory": "none", "cost": 100.00, "service_type": "Manual", "description": "Register Micro, Small, and Medium Enterprises under Udyam (MSME)."},
        {"name": "PVC Card Maker Tool", "slug": "pvcmaker", "category": "Other Services", "subcategory": "none", "cost": 150.00, "service_type": "Manual", "description": "Submit a document to be professionally formatted into a standard CR-80 PVC Card layout."},
        {"name": "CIBIL Credit Score Report", "slug": "cibil_score", "category": "Other Services", "subcategory": "none", "cost": 120.00, "service_type": "Automated", "description": "Instantly fetch complete CIBIL credit score and details report."},
    ]
    for s in services:
        Service.objects.get_or_create(
            slug=s['slug'],
            defaults={
                'name': s['name'],
                'category': s['category'],
                'subcategory': s['subcategory'],
                'cost': s['cost'],
                'service_type': s['service_type'],
                'description': s['description']
            }
        )

def remove_services(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    Service.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_services, reverse_code=remove_services),
    ]
