# Generated by Django 4.2 on 2026-07-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260705_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_OTP', 'Pending OTP Verification'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
    ]
